version: '3' 

services:
  emp3-web-docker:
    image: openkbs/emp3-web-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emp3-web-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
#    ports:
#      - 8080:8080
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace

