version: '3' 

services:
  emp3-web-docker:
    image: openkbs/emp3-web-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emp3-web-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace

